"""Retriever over the portfolio knowledge base.

Loads the saved JSON store and answers similarity queries, returning
`[{text, source, score}]`. Uses FakeEmbedder + InMemoryVectorStore by default
so it works fully offline with no API key. If the saved store is missing, it
builds one on the fly from the portfolio repos.
"""
from __future__ import annotations

import logging
from pathlib import Path

from config import get_settings

from .embedder import Embedder, FakeEmbedder
from .ingest import ingest_portfolio
from .store import InMemoryVectorStore

logger = logging.getLogger(__name__)


class Retriever:
    def __init__(self, store: InMemoryVectorStore, embedder: Embedder) -> None:
        self._store = store
        self._embedder = embedder

    def retrieve(self, query: str, k: int = 5) -> list[dict]:
        query_vec = self._embedder.embed(query)
        results = self._store.search(query_vec, k=k)
        out: list[dict] = []
        for doc, score in results:
            meta = doc.get("metadata", {})
            out.append(
                {
                    "text": doc.get("text", ""),
                    "source": meta.get("source", ""),
                    "kind": meta.get("kind", ""),
                    "score": float(score),
                }
            )
        return out


#: Doc kinds that are LEARNED at runtime rather than derived from the repos, and so
#: cannot be regenerated by an ingest. Currently just winning proposals.
LEARNED_KINDS = frozenset({"win"})


def _carry_over_learned(store: InMemoryVectorStore, previous_path: str | None) -> int:
    """Re-add learned docs from an existing store into a freshly built one.

    ``append_winning_proposal_to_kb`` writes ``kind="win"`` docs straight into the JSON
    store, and they exist nowhere else — there is no repo, no file, nothing to re-derive
    them from. A rebuild that starts from a bare ``InMemoryVectorStore`` therefore
    deletes every win the system has ever learned from, permanently and silently. The
    only visible symptom is that proposals quietly stop citing what actually closed,
    which reads as the pitch getting worse rather than as data loss.

    Adding one portfolio project should not cost the entire win history, so the rebuild
    carries them across.
    """
    if not previous_path or not Path(previous_path).is_file():
        return 0
    try:
        previous = InMemoryVectorStore.from_file(previous_path)
    except Exception as exc:  # noqa: BLE001 - a corrupt store must not block a rebuild
        logger.warning("build_store: could not read %s to preserve wins: %s", previous_path, exc)
        return 0

    learned = [
        doc
        for doc in previous.docs
        if (doc.get("metadata") or {}).get("kind") in LEARNED_KINDS
    ]
    if learned:
        store.add(learned)
        logger.info("build_store: carried over %d learned doc(s)", len(learned))
    return len(learned)


def build_store(
    repos_path: str, embedder: Embedder, *, preserve_from: str | None = None
) -> InMemoryVectorStore:
    """Ingest + embed the portfolio into a fresh in-memory store.

    ``preserve_from`` is the path of the store being replaced; learned docs found there
    are carried into the new one. See :func:`_carry_over_learned`.
    """
    docs = ingest_portfolio(repos_path)
    store = InMemoryVectorStore(dim=embedder.dim)
    embedded = [
        {
            "text": d["text"],
            "metadata": {"source": d["source"], "kind": d["kind"]},
            "vector": embedder.embed(d["text"]),
        }
        for d in docs
    ]
    store.add(embedded)
    _carry_over_learned(store, preserve_from)
    return store


def get_retriever() -> Retriever:
    """Load the saved KB (building from portfolio if the JSON store is missing)."""
    settings = get_settings()
    embedder: Embedder = FakeEmbedder()
    store_path = Path(settings.rag_store_path)

    if store_path.is_file():
        store = InMemoryVectorStore.from_file(str(store_path))
    else:
        store = build_store(settings.portfolio_repos_path, embedder)
    return Retriever(store, embedder)
